apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: dev
spec:
  type: LoadBalancer
  ports:
  - port: 8081  
    targetPort: 8081  # Match the port in your deployment
  selector:
    app: petclinic
