apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app-qa
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: 905418425077.dkr.ecr.ap-south-1.amazonaws.com/dev/petclinic:842aefe-14
        ports:
        - containerPort: 8081 
        env:
        - name: SERVER_PORT   
          value: "8081"
        - name: MYSQL_URL
          valueFrom:
            configMapKeyRef:
              name: app-config-qa
              key: MYSQL_URL
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets-qa
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets-qa
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config-qa
              key: MYSQL_DATABASE
